package com.zhiyin.plugins.ui.codeGenerator

data class Field(
    var name: String,
    var type: String,
    var length: Int = 0,
    var i18nKey: String? = null,
    var i18nChs: String = "",
    var i18nEn: String? = null,
    var isQueryField: Boolean = false,
    var isRequired: Boolean = false,
    var easyuiClass: String? = null,
    var isNullable: Boolean = false,
    var isPrimaryKey: Boolean = false,
    var isDialogField: Boolean = true,
    var isAutoIncrement: Boolean = false,
    var defaultValue: String? = null,
    var isUnique: Boolean = false,
    var isIndex: Boolean = false,
    var isForeignKey: Boolean = false,
    var foreignKeyTable: String? = null,
    var foreignKeyColumn: String? = null,
    var foreignKeyOnDelete: String? = null,
    var foreignKeyOnUpdate: String? = null,
    var isUnsigned: Boolean = false,
    var isZeroFill: Boolean = false,
    var isBinary: Boolean = false,
    var isComment: Boolean = false,
    var comment: String = "",
    var isTimestamp: Boolean = false,
    var isCreatedAt: Boolean = false,
    var isUpdatedAt: Boolean = false,
    var isDeletedAt: Boolean = false,
    var isSoftDelete: Boolean = false,
    var isJson: Boolean = false,
    var isJsonb: Boolean = false,
    var isArray: Boolean = false,
    var isEnum: Boolean = false,
) {
    companion object {
        // Factory method for creating instances with default values
        @JvmStatic
        fun createDefault(): Field {
            return Field(
                name = "",
                type = "",
                length = 0,
                i18nKey = null,
                i18nChs = "",
                i18nEn = null,
                isQueryField = false,
                isRequired = false,
                easyuiClass = null,
                isNullable = false,
                isPrimaryKey = false,
                isDialogField = true,
                isAutoIncrement = false,
                defaultValue = null,
                isUnique = false,
                isIndex = false,
                isForeignKey = false,
                foreignKeyTable = null,
                foreignKeyColumn = null,
                foreignKeyOnDelete = null,
                foreignKeyOnUpdate = null,
                isUnsigned = false,
                isZeroFill = false,
                isBinary = false,
                isComment = false,
                comment = "",
                isTimestamp = false,
                isCreatedAt = false,
                isUpdatedAt = false,
                isDeletedAt = false,
                isSoftDelete = false,
                isJson = false,
                isJsonb = false,
                isArray = false,
                isEnum = false,
            )
        }
    }
}